keys:
  - &admin_john age1spzeve3mpjm264nqdnszwv2u3vurhmevw5dwsfz6d57xsgp33v7smx8kg6
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_john