qbittorrent-webui-password-pbkdf2: ENC[AES256_GCM,data:6jdkaCuAX1q8VSEPUHnZ/8CdWYx5d6de5OOKLq4vNYeQH2b9,iv:zCQNirbb6lARvnjZmvITIX1FEKW5Kn5Dg/fZeo/evck=,tag:OuLHYZAdrtLQXpq8A/t/bg==,type:str]
sops:
    age:
        - recipient: age1spzeve3mpjm264nqdnszwv2u3vurhmevw5dwsfz6d57xsgp33v7smx8kg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q2swVzJESEpOcEIyWUZx
            Qm5PUEYvaHI0OWl3ZFM0TjZxbTRlV2s1bndFCmYxZTl5SlpJOHh4OXBWMW8rV2Zs
            QmJMUE41elhWUVVEN1BtU1RoN2xQQjQKLS0tIEw0TzNXNTdXSVVqeE5wWWh4UjUr
            K0hTK0NPaUR3OFBQSC94czljcmdTV1kKBtuwQqZqQrtjDugKmDj/o60O9Al/RuSn
            XVyS6SGAmXUR/rpC6Z6261XP058FmknIltp5ZzL9n1SIqGfUV6U6aw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1600ryfh00hsxduumfn6flu8xwtn8c70t765srq5xzndpe5ctc3rsefv0j8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSEVpVTZCTlNLYVNoNkNI
            MXNUKzk4WnhWNzVHNjc3RmplOWhyZzlvNldNClhRMWEzSUtwTU13cHIxbDRrdTdW
            TGI5c3E3TlExek5lc1QzaktJRGc4S0EKLS0tIEFzVDVkS3VVamVYTWM0dFNLRXMx
            N01qSWt1dU91eE1Lc0FXVDVDSmVqc0kKvkTK7fMdtOz3UnEF/qyj7MZQAyi3ARxH
            M3JFyl6VgOa1h1fVGtXUdK0ZUXXstGPuso5XGvi9TAxkyw1vAjwO1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T13:39:31Z"
    mac: ENC[AES256_GCM,data:sGv44w884JqRgij+TP6JDYHxFZMyimGpIHnmf3iLaCPM6ddo0knmONVNKxDxxo+ADjBkKkkroV5i+RckLQygUntAcJ1N6gAxtdAyTXZc8T/8EF6mYo97BkKuk0dteHUgSTWA+gxQo7QCdO+gDNtBKz0LnKb5RDTS59c/bcCels8=,iv:97eYNrLBkk4yzM9oyL8i702pUpoqs0cFbuvExBNrf8o=,tag:ePmcdxAvJSZZR75yOqW6WQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
