qbittorrent-webui-password-pbkdf2: ENC[AES256_GCM,data:XRn5Sa/bzca8ncSCg0r/uFZyhu7/wknAk5ZDRgOm+ldLO+mOZqpZrxWA3mMXVR967UNRPQFEyGSvLqinlMoh1J/1cmSd31mzyVKkvwRN9O7wL+aFXlvv8rM8CdwOkMn0uUQEYvZfq3yrG9HsPaVmBihCjdjD6FVrmYCBDcg=,iv:vfFHnO5xToE4bikOoGg/Hw7CWMRhpmq2TzLbUX3B6mg=,tag:qzcjikDI6iqXCtjLYrHcNA==,type:str]
sops:
    age:
        - recipient: age1spzeve3mpjm264nqdnszwv2u3vurhmevw5dwsfz6d57xsgp33v7smx8kg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q2swVzJESEpOcEIyWUZx
            Qm5PUEYvaHI0OWl3ZFM0TjZxbTRlV2s1bndFCmYxZTl5SlpJOHh4OXBWMW8rV2Zs
            QmJMUE41elhWUVVEN1BtU1RoN2xQQjQKLS0tIEw0TzNXNTdXSVVqeE5wWWh4UjUr
            K0hTK0NPaUR3OFBQSC94czljcmdTV1kKBtuwQqZqQrtjDugKmDj/o60O9Al/RuSn
            XVyS6SGAmXUR/rpC6Z6261XP058FmknIltp5ZzL9n1SIqGfUV6U6aw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1600ryfh00hsxduumfn6flu8xwtn8c70t765srq5xzndpe5ctc3rsefv0j8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSEVpVTZCTlNLYVNoNkNI
            MXNUKzk4WnhWNzVHNjc3RmplOWhyZzlvNldNClhRMWEzSUtwTU13cHIxbDRrdTdW
            TGI5c3E3TlExek5lc1QzaktJRGc4S0EKLS0tIEFzVDVkS3VVamVYTWM0dFNLRXMx
            N01qSWt1dU91eE1Lc0FXVDVDSmVqc0kKvkTK7fMdtOz3UnEF/qyj7MZQAyi3ARxH
            M3JFyl6VgOa1h1fVGtXUdK0ZUXXstGPuso5XGvi9TAxkyw1vAjwO1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:22:02Z"
    mac: ENC[AES256_GCM,data:RpafU3do+xvHfGw9hDBc0mvNFLeD8CZumz8oBaK0AW+L3wkeqJpJoG7w6NKVP65zNCCxTotlRT9F1iJGtq87dIBmR7EZShHWqPZ0eg5lXrq2R1Uf8sPnyjH8YI6WuY9HSmkK5nmBzevZ3PyZoSWgrLWt6CXrRfzfjVtcebllpYY=,iv:VJU71L/pLDP7n+erVm19KcaYDRLMyYZlanxNP6fZ/0w=,tag:CIlSvORL7WvL6V2D5Pg1+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
