qbittorrent-webui-password-pbkdf2: ENC[AES256_GCM,data:sz2ArfI2Uz71ytkoryBs+Y718Xj/BB7aRn2WXsA3NKtoKFp7kaP+NsLKHIQjY2CIcutZD1ayiuOAyRWpTXpweOp4a1zDriydNEMbCIlX8gcGgrAnC3bdQmRrta/1aT3RqlZKMsOFnY/CRqNbqXdaWN0DMrjd3cddSfiOKOA=,iv:huiaC4ikZ0uq0/v10seBQmsPOsGMDHZmo2raTnFw6S8=,tag:dToIhiKvoHlHDLtI6k7SRg==,type:str]
sops:
    age:
        - recipient: age1spzeve3mpjm264nqdnszwv2u3vurhmevw5dwsfz6d57xsgp33v7smx8kg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q2swVzJESEpOcEIyWUZx
            Qm5PUEYvaHI0OWl3ZFM0TjZxbTRlV2s1bndFCmYxZTl5SlpJOHh4OXBWMW8rV2Zs
            QmJMUE41elhWUVVEN1BtU1RoN2xQQjQKLS0tIEw0TzNXNTdXSVVqeE5wWWh4UjUr
            K0hTK0NPaUR3OFBQSC94czljcmdTV1kKBtuwQqZqQrtjDugKmDj/o60O9Al/RuSn
            XVyS6SGAmXUR/rpC6Z6261XP058FmknIltp5ZzL9n1SIqGfUV6U6aw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1600ryfh00hsxduumfn6flu8xwtn8c70t765srq5xzndpe5ctc3rsefv0j8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSEVpVTZCTlNLYVNoNkNI
            MXNUKzk4WnhWNzVHNjc3RmplOWhyZzlvNldNClhRMWEzSUtwTU13cHIxbDRrdTdW
            TGI5c3E3TlExek5lc1QzaktJRGc4S0EKLS0tIEFzVDVkS3VVamVYTWM0dFNLRXMx
            N01qSWt1dU91eE1Lc0FXVDVDSmVqc0kKvkTK7fMdtOz3UnEF/qyj7MZQAyi3ARxH
            M3JFyl6VgOa1h1fVGtXUdK0ZUXXstGPuso5XGvi9TAxkyw1vAjwO1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T00:37:55Z"
    mac: ENC[AES256_GCM,data:MPdOd1I6X9OC0yEZPLouHwmSgkdJVKsoTLUmIY0VPYF4kDRqSbgsb4RsiBaHK+tGCJ9+uImUhhIeVQoFeL32Zy5JBRYxw+3x7S/ZJNlQL/6nhWKyirtNXzHCrE0DuKsqs6TK8XgpQks/77ytXJvlvKTNcctjBRRTElq12ys51x8=,iv:V6fyDduYQym+M57/Dh+jE58d5IgWnEf/kGR5lZVPDFQ=,tag:eg433OUmgsaFREme7dQayw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
